apiVersion: v1
kind: Secret
metadata:
  name: gnc-redis-secret
  namespace: layer8
  labels:
    app: gnc-redis
    app.kubernetes.io/name: gnc-redis
    app.kubernetes.io/component: database
type: Opaque
stringData:
  # Redis Password
  REDIS_PASSWORD: "S3cretP@ssw0rd"

  # Redis URL
  REDIS_URL: "redis://:S3cretP@ssw0rd@gnc-redis.layer8.svc.cluster.local:6379/0"
