apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gnc-redis-pvc
  namespace: layer8
  labels:
    app: gnc-redis
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
  storageClassName: standard-rwo
