apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gnc-postgres-pvc
  namespace: layer8
  labels:
    app: gnc-postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
  storageClassName: standard-rwo
