apiVersion: v1
kind: Secret
metadata:
  name: gnc-backend-secret
  namespace: layer8
  labels:
    app: gnc-backend
    app.kubernetes.io/name: gnc-backend
    app.kubernetes.io/component: backend
type: Opaque
stringData:
  # Backend Configuration
  PORT: "8080"
  API_URL: "0.0.0.0:8080"
  ENV: "DEV"

  # Database Configuration
  DB_ADDR: "postgres://globeandcitizen:masterkey@gnc-postgres.layer8.svc.cluster.local:5432/stats-api-go?sslmode=disable"
  DB_HOST: "gnc-postgres.layer8.svc.cluster.local"
  DB_USER: "globeandcitizen"
  DB_PASSWORD: "masterkey"
  DB_NAME: "stats-api-go"
  DB_MAX_OPEN_CONNS: "30"
  DB_MAX_IDLE_CONNS: "30"
  DB_MAX_IDLE_TIME: "15m"

  # Redis Configuration
  REDIS_URL: "redis://:S3cretP@ssw0rd@gnc-redis.layer8.svc.cluster.local:6379/0"

  # Cloudinary Configuration
  CLOUDINARY_URL: "cloudinary://953177367974311:lPRkA-981I_8j0-s4GXzYg2k79w@dhukt5f3r"

  # Basic Auth
  AUTH_BASIC_USERNAME: "admin"
  AUTH_BASIC_PASSWORD: "admin"
