# IMPORTANT: THESE SECRETS ARE ONLY FOR DEVELOPMENT
apiVersion: v1
kind: Secret
metadata:
  name: spa-backend-secret
  namespace: layer8
type: Opaque
stringData:
  HOST: "0.0.0.0"
  PORT: "3000"
  JWT_SECRET: "spa-backend-jwt-secret"
  # LAYER8_URL: "http://35.206.226.108:5001"
  LAYER8_URL: "https://authdev.gc.layer8proxy.net"
  # LAYER8_CALLBACK_URL: "http://35.206.255.121:5173/oauth2/callback"
  LAYER8_CALLBACK_URL: "https://authdev.gc.layer8proxy.net/oauth2/callback"
  # LAYER8_RESOURCE_URL: "http://35.206.226.108:5001/api/user"
  LAYER8_RESOURCE_URL: "https://authdev.gc.layer8proxy.net/api/user"
  LAYER8_UUID: "b954b2e5-ab41-4747-b7ed-15874414032d"
  LAYER8_SECRET: "7e5d69dff7c12ba560c508af10302690"
  NODE_ENV: "development"
